version = 0.1
[default.deploy.parameters]
stack_name = "cognito-passwordless-auth-flow"
resolve_s3 = true
s3_prefix = "cognito-passwordless-auth-flow"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "UserPoolName=\"passwordless-user-auth\""
image_repositories = []
